services:
  - name: mangarage
    plan: free
    type: web
    env: node
    repo: https://github.com/lsanc0043/mangarage
    buildCommand: cd client && npm install && node src/components/test.mjs && npm run build && cd ../server && npm install
    startCommand: cd server && node ./node_modules/db-migrate/bin/db-migrate up && npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

databases:
  - name: db
    plan: free
    ipAllowList: []