services:
  - name: mangarage
    plan: free
    type: web
    env: node
    repo: https://github.com/lsanc0043/mangarage
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && psql -h dpg-cdq4l6sgqg47to0i6qjg-a.oregon-postgres.render.com -U db_3wia_user db_3wia && gxKFGK8yrRhOghWSKbjbDpHLy9YrptJp && npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

databases:
  - name: db
    plan: free
    ipAllowList: []