const MangaDump = [
  `INSERT INTO public.manga (id, title, author, year, status, last_updated, description, genres, cover, characters) VALUES (1, 'A Returner''s Magic Should Be Special', 'Usonan (우소난)', '2018', 'ongoing', '2022-11-13T11:05:25+00:00', '"Now that I''m back, I won''t allow my loved ones to die again!" 
  The Shadow Labyrinth - the deadliest catastrophe humanity has ever known. Desir Arman, one of the six remaining survivors of mankind, is inside the Labyrinth. The six of them attempt to clear the final level of the Labyrinth but ultimately fail, and the world comes to an end. 
  However, when Desir thought he would meet his demise, what appears before him is the world... thirteen years ago?! 
  Desir is returned to the past, back to the time when he is enrolled at the nation''s finest magic academy, Havrion. He is reunited with his precious friends, and he is determined to change the past to save the world and his loved ones...! 
  Three years remain before the emergence of the Shadow World! Change the past and gather powerful comrades to save mankind!', '{Action,Comedy,Adventure,Fantasy,"Slice of Life"}', 'https://mangadex.org/covers/6a468761-5bd6-4de0-a0cb-47cb456ac2e0/6fede191-79a0-453b-8b8d-939ab067f657.jpg', '{"Desir ARMAN","Adjest KINGSCROWN","Pram SCHNEIDER","Romantica ERU","Swan KATARINA"}');
    `,
  `INSERT INTO public.manga (id, title, author, year, status, last_updated, description, genres, cover, characters) VALUES (2, 'Ace of Diamond', 'Terajima Yuuji', '2006', 'completed', '2022-11-02T02:50:10+00:00', 'Eijun Sawamura had his heart set on the middle-school national baseball championships. But his team is eliminated thanks to a wild pitch thrown by Eijun himself. 
  He''s planning to go to high school with his teammates and try again next year when he''s scouted by the famous Seido High School baseball team. When he goes for a campus visit, he finds himself on the receiving end of a baptism by fire! His experience forming a battery with up-and-coming catcher Miyuki rekindles his passion for baseball!!', '{Comedy,Sports,Drama}', 
  'https://mangadex.org/covers/60879eb7-3845-4dff-b86d-5a612108053b/50f22552-4a61-4df6-9fde-b797095527f6.jpg', '{"Eijun SAWAMURA","Kazuya MIYUKI","Satoru FURUYA","Haruichi KOMINATO","Haruno YOSHIKAWA","Kouichirou TANBA","Rei TAKASHIMA","Ryousuke KOMINATO","Shinji KANEMARU","Tesshin KATAOKA","Tetsuya YUUKI","Tooru MASUKO","Wataru KARIBA","Youichi KURAMOCHI","Akagi Principal",
  "Akiko OOWADA","Akira NAGAO","Ataru NAKATA","Carlos Toshiki KAMIYA","Daiki KONDOU","Eijirou SAKAKI","Eijun''s Father","Eijun''s Mother","Eitoku SAWAMURA","Fujio MINE","Gou WAKABAYASHI","Hideaki TOUJOU","Hiroki KONDOU","Hiromi TACHI","Hiromitsu OCHIAI","Hiroshige KUNITOMO","Hiroshi ONO","Hiroshi OOSHIMA","Hisashi WATANABE","Ichirou ARAKI","Ichirou SAKAI","Ippachi OKAMOTO",
  "Itsuki TADANO","J. Animal M.","Jun ISASHIKI","Junzou SEKIGUCHI","Kaname MANAKA","Katsuyuki SHIRAKAWA","Kazuma AKIBA","Kazuyoshi OOTA","Keiji HIRANO","Keisuke MIYAUCHI","Kengo INUI","Kengo KAWASHIMA","Kenjirou SHIRASU","Kenta MAEZONO","Kento FUKUI","Ken YAMAGUCHI","Kiyokuni AZUMA","Kouji YABE","Kousei AMAHISA","Koushuu OKUMURA","Kouta INUBUSHI","Kouzou NITTA","Masaaki INAMOTO",
  "Masaaki KADOTA","Masashi YUUKI","Masatoshi HARADA","Megumi YAGI","Mei NARUMIYA","Nao MATSUBARA","Naomichi SEKI","Naoyuki ZAIZEN",Ninomiya,"Norifumi KAWAKAMI","Raichi TODOROKI","Raizou TODOROKI","Rei KIJIMA","Ryota MIMURA","Ryou HIRAHATA","Sachiko UMEMOTO","Sanae KIKUKAWA",Sano,"Seiichi UMEMIYA","Shinichirou MASU","Shinji AKAMATSU","Shouji HIGASA","Shunpei SANADA","Shunshin YOU",
  "Shuuji HIGASHIO","Tadahiro KANEDA","Taiyou MUKAI","Takahiro HIRAKAWA","Takahiro OOMAE","Takako FUJIWARA","Takeru ASOU","Takuma SETO","Tatsuomi HARA","Toshihiko TAHARA","Tsubasa HIRAI","Tsunematsu OGAWA", "Wakana AOTSUKI","Yasushi KUDOU","Yoshimi HIDOKORO","Yousuke MAKI","Yui NATSUKAWA","Yuu Chris TAKIGAWA","Yuuta MISHIMA"}');`,
];

export default MangaDump;
